import type { PredictiveSourceRef } from "./predictiveTypes";

export const PREDICTIVE_SOURCES: PredictiveSourceRef[] = [
  {
    id: "MARCOS_BOOK_CH22_SECONDARY",
    author: "Marcos Monteiro",
    work: "Introdução à Astrologia Ocidental — Cap. 22",
    dateOrVersion: "edição revista/aumentada recuperada",
    locator: "Progressões secundárias",
    rule: "Um dia após o nascimento corresponde a um ano de vida; importam as progressões individuais e seus encontros com posições natais, não um mapa progredido autônomo.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_2026_PROGRESSIONS_CONJ_OPP",
    author: "Marcos Monteiro",
    work: "material público/transcrição recuperada",
    dateOrVersion: "2026-04-10",
    locator: "progressions",
    rule: "Na prática atual de progressões secundárias, considerar somente conjunção e oposição para evitar testemunhos irrelevantes.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_BOOK_SOLAR_RETURN_BIRTHPLACE",
    author: "Marcos Monteiro",
    work: "Introdução à Astrologia Ocidental — mapas de retorno",
    dateOrVersion: "edição revista/aumentada recuperada",
    locator: "Revolução Solar",
    rule: "No procedimento descrito por Marcos, a Revolução Solar é aberta para o local de nascimento; o local onde o nativo passa o aniversário não substitui esse referencial.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_2024_PREDICTIVE_HIERARCHY",
    author: "Marcos Monteiro",
    work: "curso de astrologia natal — módulo de predição (transcrição recuperada)",
    dateOrVersion: "2024-10-14",
    locator: "progressions → solar return → lunar return → derived lunar return",
    rule: "A Solar não deve ser julgada isoladamente; Lunar e Lunar Derivada refinam progressões e Solar. DLR encurta/refina a janela e é julgada como a Lunar comum.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_2026_TRANSIT_TRIGGER",
    author: "Marcos Monteiro",
    work: "material público/transcrição recuperada",
    dateOrVersion: "2026-04-02",
    locator: "trânsitos",
    rule: "Trânsito é no máximo gatilho/marcador; outras técnicas mostram se a possibilidade está carregada e para onde aponta.",
    coverage: "SOURCE_LOCKED_WITH_OPERATIONAL_GATE",
  },
  {
    id: "MARCOS_RECENT_PROFECTION_CAUTION",
    author: "Marcos Monteiro",
    work: "curso/material recente recuperado",
    dateOrVersion: "2024–2026",
    locator: "profections",
    rule: "A profecção é usada, mas o regente anual não deve ser automaticamente supervalorizado; o foco é a profecção em si e o conjunto do mapa.",
    coverage: "TRADITIONAL_STANDARD_MECHANICS",
  },
  {
    id: "FRAWLEY_CURRENT_NATAL_PREDICTION",
    author: "John Frawley",
    work: "Natal & Electional Astrology / current course materials",
    dateOrVersion: "verificado em 2026-08-31",
    locator: "progressions; return charts; profections; lunar/derived lunar material",
    rule: "Progressões, retornos e profecções são técnicas preditivas do perfil atual; os retornos são lidos contra o radix, com testemunhos concretos e mudanças de condição.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "FRAWLEY_NATAL_PLACIDUS",
    author: "John Frawley",
    work: "The Horary Textbook / The Real Astrology Applied",
    dateOrVersion: "recovered published corpus",
    locator: "house systems",
    rule: "Regiomontanus is used for horary; Frawley explicitly uses Placidus for natal work and non-horary charts.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "FRAWLEY_FIVE_PRIMARY_DIRECTORS",
    author: "John Frawley",
    work: "The Real Astrology Applied",
    dateOrVersion: "2002 edition / recovered corpus",
    locator: "Natal Astrology, pp. 123-126 parsed",
    rule: "The five main directing/progressing points are Sun, Moon, Ascendant, Midheaven and Part of Fortune. Watch them hitting natal planets, house cusps, fixed stars, or changing terms; other planetary meetings are secondary unless authorized by the main points.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "FRAWLEY_ORWELL_RELATIONAL_EVIDENCE",
    author: "John Frawley",
    work: "public natal extract — George Orwell",
    dateOrVersion: "current public extract verified 2026-08-31",
    locator: "progressed/return examples",
    rule: "Materializar contatos progredido↔progredido, progredido↔natal, cúspide/ângulo de retorno↔radix, antíscio e mudanças de dignidade/condição.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_BOOK_SOLAR_CONDITION_LIMITS",
    author: "Marcos Monteiro",
    work: "Introdução à Astrologia Ocidental",
    dateOrVersion: "edição revista/aumentada recuperada",
    locator: "dignidade acidental — cazimi, combustão e sob os raios",
    rule: "Cazimi dentro do raio solar de 17,5 minutos; combustão até 8°30 no mesmo signo; sob os raios até 17°. O motor materializa a condição e a distância aos limites, sem transformar a proximidade temporal da mudança em score.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "FRAWLEY_APPLIED_SOLAR_CONDITION_LIMITS",
    author: "John Frawley",
    work: "The Real Astrology Applied",
    dateOrVersion: "recovered published corpus",
    locator: "solar conditions",
    rule: "Preserve Frawley's published solar-condition boundaries separately from Marcos, including the 17.5-degree under-sunbeams boundary used in the recovered Applied corpus. Return judgement then distinguishes static condition from recent/imminent change.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "FRAWLEY_RETURN_JUDGMENT_GRAMMAR",
    author: "John Frawley",
    work: "The Real Astrology Applied",
    dateOrVersion: "recovered published corpus",
    locator: "Solar and Lunar Returns — return-chart judgement",
    rule: "Return charts are read mainly against the radix. Materialize return-planet house placement, internal aspects, receptions, planets within 1–2° of return cusps, radical house rulers in their return positions, angle repetition/mirroring, nodes on angles, and cross-chart connections; a return cannot create an event absent from the nativity.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "FRAWLEY_ORWELL_RETURN_CHANGE_EVIDENCE",
    author: "John Frawley",
    work: "Extract from Natal Volume: George Orwell",
    dateOrVersion: "AA Journal extract / public Frawley site",
    locator: "Solar Return 1936; Lunar Return 13 May 1937",
    rule: "Orwell case source-locks internal antiscion in a Solar Return, return-cusp antiscion to the angle axis, South Node involvement, Lunar ASC on natal Mars, and especially recent/imminent changes of dignity/reception rather than static dignity/reception alone.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_PROGRESSIONS_PARTS_ANTISCIA_EXAMPLES",
    author: "Marcos Monteiro",
    work: "Notas astrológicas / exemplos públicos de Ciro Gomes e Jair Bolsonaro",
    dateOrVersion: "examples recovered in corpus/web archive",
    locator: "secondary progressions for election periods",
    rule: "In concrete secondary-progression examples Marcos progresses Fortune, Spirit and other relevant Arabic Parts from the progressed factors, uses progressed DSC/MC/cusps, and judges conjunction/opposition including antiscion contacts. Fortune and Spirit can move roughly lunar-scale during a year; they must not be replaced by a ~1°/year solar-arc translation of the natal lot.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_SOLAR_RETURN_PARTS_ARC_EXAMPLES",
    author: "Marcos Monteiro",
    work: "Notas astrológicas — exemplos de Revoluções Solares",
    dateOrVersion: "examples recovered in public notes",
    locator: "Partes natais, calculadas e por arco natal em mapas separados",
    rule: "Marcos aplica Partes em Revoluções e usa explicitamente Partes por arco natal além da Fortuna (por exemplo Amor, Vitória e Cativeiro em casos publicados). O motor materializa, para as sete Partes source-locked, posição natal na Revolução, posição recalculada pelos fatores da Revolução e posição por arco natal, mantendo cada variante identificada.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_SOLAR_RETURN_CIRO_CASE_EVIDENCE",
    author: "Marcos Monteiro",
    work: "Notas astrológicas — Revolução Solar de Ciro Gomes",
    dateOrVersion: "2017/2018 example recovered",
    locator: "Solar Return: repeated ASC/DSC axis; nodal antiscion; Mercury dignity change",
    rule: "A concrete Marcos return example checks repetition of the return ASC/DSC axis against the natal axis, nodal antiscion links, and a recent change of essential condition of a relevant natal house ruler; the return refines what progressions already show.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "TRADITIONAL_ANNUAL_PROFECTION_STANDARD",
    author: "Traditional mechanics",
    work: "annual profection standard mechanics",
    locator: "one sign/house per completed year",
    rule: "Avançar o foco anual um signo/casa por ano completo e obter o regente do signo profectado; planetas natais permanecem em suas posições natais.",
    coverage: "TRADITIONAL_STANDARD_MECHANICS",
  },
  {
    id: "MARCOS_YOUTUBE_EN_PREDICTION_MODULE",
    author: "Marcos Monteiro",
    work: "YouTube EN — Natal Astrology Course / Prediction module",
    dateOrVersion: "corpus novo recuperado em 2026-09-01",
    locator: "module 3: periods → secondary progressions → Solar → Lunar → DLR; transits",
    rule: "Na prática do curso, progressões secundárias são priorizadas sobre direções primárias por praticidade/confiabilidade do cálculo; Solar, Lunar e DLR refinam sucessivamente a investigação temporal; trânsitos não ocupam o papel principal.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_PROGRESSIONS_ANGLE_USAGE_EXAMPLES",
    author: "Marcos Monteiro",
    work: "Notas astrológicas / exemplos públicos de progressões",
    dateOrVersion: "exemplos recuperados 2018–2024",
    locator: "Ciro Gomes; Bolsonaro; Pedro II — ângulos progredidos",
    rule: "Marcos usa explicitamente Ascendente/Descendente e Meio-Céu progredidos e, em exemplo anual, orienta avançar mentalmente Sol/ASC/MC em cerca de um grau. Isso source-locka o uso e a escala anual dos ângulos, mas não nomeia uma constante/setting matemático exato como Naibod.",
    coverage: "SOURCE_LOCKED_WITH_OPERATIONAL_GATE",
  },
  {
    id: "FRAWLEY_NAIBOD_RA_SECONDARY_ATTESTATION",
    author: "MathAstro audit",
    work: "Kathryn Silvestre — Ted Kennedy/Chappaquiddick; AstroConnexions — reconstruction of John Frawley Culpeper lecture",
    dateOrVersion: "secondary attestations recovered 2013/2016; verified 2026-09-01",
    locator: "secondary progressions / software setting",
    rule: "Two independent secondary witnesses from Frawley-linked practice attest the same setting: Kathryn Silvestre, who completed Frawley's natal apprenticeship, instructs 'Naibod in RA'; AstroConnexions' reconstruction of Frawley's Culpeper lecture states that John recommends 'Naibod in RA or Mean Solar Arc in RA (both are the same)'. This matches MathAstro's mean-solar-arc-in-right-ascension angle progression. It is secondary attestation, not a recovered primary quotation from Frawley.",
    coverage: "SOURCE_LOCKED_WITH_OPERATIONAL_GATE",
    evidenceLevel: "SECONDARY",
  },
  {
    id: "MARCOS_FORTUNE_TEMPORAL_CURRENT",
    author: "Marcos Monteiro",
    work: "material público/transcrição recuperada",
    dateOrVersion: "2026-04-10",
    locator: "Parte da Fortuna em natal, progressões e Revolução Solar",
    rule: "Marcos afirma que acompanha a Parte da Fortuna em progressões e, em Revoluções Solares, verifica a posição natal, a posição calculada para a revolução e a posição por arco natal atribuída a Frawley.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "MARCOS_FIXED_STARS_TEMPORAL_COURSE",
    author: "Marcos Monteiro",
    work: "Curso de Estrelas Fixas",
    dateOrVersion: "corpus novo recuperado em 2026-09-01",
    locator: "exemplos com progressões, Revolução Solar e Revolução Lunar; regras de conjunção por signo/orbe",
    rule: "Estrelas fixas podem ser materializadas também em técnicas temporais; o motor usa posições da época e preserva a regra de mesmo signo e os limites documentados de 1° para estrelas comuns e até 3° para principais/reais, sem transformar isso em interpretação autônoma.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "GUGU_COSMOLOGY04_PERIOD_VALUES",
    author: "Luiz Gonzaga de Carvalho Neto",
    work: "Curso de Cosmologia e Astrologia Medieval 04",
    dateOrVersion: "corpus novo recuperado em 2026-09-01",
    locator: "períodos planetários: Lua 25; Sol 19; Mercúrio 20; Vênus 8; Marte 15; Júpiter 12; Saturno 30",
    rule: "Os mesmos números planetários regem anos, meses, dias e horas; anos são simbólicos de 360 dias e meses de 30 dias.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "GUGU_COSMOLOGY04_ZODIAC_SEQUENCE",
    author: "Luiz Gonzaga de Carvalho Neto",
    work: "Curso de Cosmologia e Astrologia Medieval 04",
    dateOrVersion: "corpus novo recuperado em 2026-09-01",
    locator: "sequência dos grandes períodos",
    rule: "O primeiro grande período parte do signo do Ascendente e os períodos seguintes avançam pela sequência dos signos; o regente de cada signo fornece a duração correspondente.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "GUGU_COSMOLOGY04_SUBDIVISIONS",
    author: "Luiz Gonzaga de Carvalho Neto",
    work: "Curso de Cosmologia e Astrologia Medieval 04",
    dateOrVersion: "corpus novo recuperado em 2026-09-01",
    locator: "anos subdivididos em meses; meses em dias; dias em horas",
    rule: "Os grandes períodos são subdivididos em escalas menores seguindo continuamente a sequência zodiacal e os mesmos números. Ao completar Peixes, a sequência zodiacal continua em Áries enquanto o período-pai ainda tiver duração.",
    coverage: "SOURCE_LOCKED_IMPLEMENTED",
  },
  {
    id: "GUGU_COSMOLOGY04_TRANSIT_SUBORDINATION",
    author: "Luiz Gonzaga de Carvalho Neto",
    work: "Curso de Cosmologia e Astrologia Medieval 04",
    dateOrVersion: "corpus novo recuperado em 2026-09-01",
    locator: "trânsitos e períodos astrológicos",
    rule: "Trânsitos não indicam acontecimentos autonomamente; sua relevância depende do período. Fatos marcantes tendem a concentrar-se perto de transições de períodos, sem orbe temporal universal fornecido. O receptor da autoridade pesa mais que o doador e a condição natal dos regentes modifica a qualidade.",
    coverage: "SOURCE_LOCKED_WITH_OPERATIONAL_GATE",
  },
];
