import type { HoraryCoverageEntry, HoraryTopic } from "./types";

export const HORARY_TOPIC_COVERAGE: Record<HoraryTopic,HoraryCoverageEntry> = {
  relationship:{status:"mechanized",ruleIds:["H1-H7","reception","perfection"],note:"Relação entre querente e outra pessoa; evento e atitude permanecem separados."},
  marriage:{status:"mechanized",ruleIds:["H1-H7","default","fertility","perfection"],note:"Casamento usa eixo I/VII, default contextual e testemunhos próprios."},
  separation:{status:"mechanized",ruleIds:["H1-H7","separating","opposition"],note:"Separação lê afastamento, mudança e qualidade do vínculo."},
  lover:{status:"mechanized",ruleIds:["H7","relationship-natural-significators"],note:"Amante é pessoa de VII; sexo/função não substitui a pessoa."},
  job_get:{status:"mechanized",ruleIds:["H10","H11-wages","H7-rival","perfection"],note:"Vaga, salário e rival são separados."},
  job_keep:{status:"mechanized",ruleIds:["fixity","VOC","sign-change"],note:"Manutenção não exige aspecto; estado e mudança são prioritários."},
  job_quality:{status:"mechanized",ruleIds:["H10-condition","H11-wages"],note:"Descritivo, sem YES/NO genérico."},
  work_relationship:{status:"mechanized",ruleIds:["boss-H10","colleague-H7","subordinate-H6","reception"],note:"Relação de trabalho é primariamente estado/recepção."},
  career_choice:{status:"mechanized",ruleIds:["alternatives","natural-rulers","derived-wages"],note:"Compara opções concretas, sem inventar profissão."},
  money:{status:"mechanized",ruleIds:["H2"],note:"Dinheiro próprio e sua condição."},
  salary:{status:"mechanized",ruleIds:["H11","arrival-H1-Moon-H2"],note:"Salário como II da X."},
  debt:{status:"mechanized",ruleIds:["source-money","arrival-H1-Moon-H2"],note:"Identifica de quem vem o dinheiro antes de julgar pagamento."},
  loan:{status:"mechanized",ruleIds:["source-money","arrival-H1-Moon-H2"],note:"Empréstimo/devolução usa a II da pessoa que detém o dinheiro."},
  investment:{status:"mechanized",ruleIds:["H2","sign-change","nodes-aux"],note:"Investimento continua sendo dinheiro próprio; trajetória de L2 é central."},
  tax:{status:"mechanized",ruleIds:["H2","H10","H11"],note:"Dinheiro do querente, governo e tesouro são materializados separadamente."},
  inheritance:{status:"mechanized",ruleIds:["2nd-from-source","arrival-H1-Moon-H2","prohibition"],note:"Herança específica não é H8 automática."},
  bet:{status:"mechanized",ruleIds:["H2","H8-bookmaker-money","profit"],note:"Aposta é pergunta de lucro, não competição esportiva se o interesse é financeiro."},
  buy_sell:{status:"mechanized",ruleIds:["H1-H7-deal","property-H4","price-H10"],note:"Negócio entre partes em I/VII; objeto e preço permanecem separados."},
  property:{status:"mechanized",ruleIds:["H4-condition","H10-price","H5-profit","H6-neighbours"],note:"Estrutura própria para imóvel."},
  lost_object:{status:"mechanized",ruleIds:["H2-or-H4","location-by-house","recovery"],note:"Localização por casa do significador; recuperação separada da localização."},
  missing_animal:{status:"mechanized",ruleIds:["H6-small","H12-large","location"],note:"Animal pequeno e grande recebem casas distintas."},
  missing_person:{status:"mechanized",ruleIds:["relation-house","location-by-placement","direction"],note:"Pessoa desaparecida é identificada pela relação ordinária; não tratada como objeto."},
  theft:{status:"mechanized",ruleIds:["suspect-house","separating-contact","antiscion-hidden"],note:"Furto passado exige testemunho passado quando não é fato conhecido."},
  lawsuit:{status:"mechanized",ruleIds:["H1-H7","judge-H10","verdict-H4"],note:"Partes, juiz e veredicto separados."},
  competition:{status:"mechanized",ruleIds:["H1-H7","accidental-strength","combustion"],note:"Us versus Them; se interesse real for aposta, roteia para lucro."},
  should_i:{status:"mechanized",ruleIds:["alternatives","compare-condition"],note:"Opções concretas comparadas sem reduzir automaticamente à VII."},
  travel:{status:"mechanized",ruleIds:["H3-or-H9","purpose-over-distance"],note:"Viagem é roteada pelo sentido/purpose, não apenas quilometragem."},
  travel_profit:{status:"mechanized",ruleIds:["journey-house","2nd-from-journey"],note:"Lucro da viagem deriva da casa da viagem."},
  study:{status:"mechanized",ruleIds:["H9-higher","H3-elementary"],note:"Nível de conhecimento distingue III e IX."},
  exam:{status:"mechanized",ruleIds:["student","school-H9","success"],note:"Exame/escola preserva pessoa e instituição."},
  knowledge:{status:"mechanized",ruleIds:["H9-or-H3","condition","profit-derived"],note:"Conhecimento e lucro do conhecimento não são a mesma coisa."},
  course:{status:"mechanized",ruleIds:["H9","teacher-H9","profit-derived"],note:"Curso/conhecimento superior em IX salvo contexto elementar."},
  health:{status:"mechanized",ruleIds:["patient","illness-cause","medical-chain"],note:"Paciente, doença, médico e tratamento separados."},
  illness:{status:"mechanized",ruleIds:["patient-condition","illness-cause"],note:"Não reduz doença a L6 genérico quando a cadeia diagnóstica é necessária."},
  doctor:{status:"mechanized",ruleIds:["7th-from-patient","doctor-condition"],note:"Médico que trata o caso é VII do paciente; médico em geral pode ser IX."},
  treatment:{status:"mechanized",ruleIds:["10th-from-patient","treatment-condition"],note:"Tratamento dado é X do paciente no canônico Frawley."},
  surgery:{status:"mechanized",ruleIds:["treatment","Mars-natural","source-variant"],note:"Marte é auxiliar natural; variantes documentais ficam explícitas."},
  pregnancy:{status:"mechanized",ruleIds:["H5","fertility","placement"],note:"Gravidez é V; mulher grávida mantém a própria casa relacional."},
  death:{status:"mechanized",ruleIds:["H8-radical","H8-turned","translation","combustion"],note:"Morte de terceiro exige VIII radical e derivada; segurança clínica permanece."},
  prison:{status:"mechanized",ruleIds:["H12-radical","H12-turned","cusp-entry","station"],note:"Estado livre/preso muda a leitura."},
  release:{status:"mechanized",ruleIds:["H12-radical","H12-turned","exit","station"],note:"Procura saída/reversão do estado de confinamento."},
  self_undoing:{status:"mechanized",ruleIds:["H12","reception","mode","sign-change"],note:"Autossabotamento/vício sem diagnóstico médico."},
  hidden_enemy:{status:"mechanized",ruleIds:["H12","reception","contact"],note:"Inimigo oculto usa XII; não inventa pessoa acusada."},
  psychic_attack:{status:"safety_limited",ruleIds:["H12","historical-grammar","no-supernatural-assertion"],note:"Somente gramática histórica; nunca confirma causalidade sobrenatural."},
  wish:{status:"mechanized",ruleIds:["H11-context","object-own-house"],note:"XI é esperança, não substitui a casa do objeto desejado."},
  dream_truth:{status:"mechanized",ruleIds:["H9","truth-testimonies"],note:"Verdade de sonho/predição é distinta de significado."},
  dream_meaning:{status:"manual_context",ruleIds:["H9","characters-ordinary-houses","house-semantic-frame"],note:"A narrativa exige interpretação semântica; depois que personagens/papéis são resolvidos, o cálculo de casas e testemunhos é mecanizado."},
  rumour:{status:"mechanized",ruleIds:["H3","truth-testimonies"],note:"Rumor/gossip em III, com regra própria de verdade."},
  news_truth:{status:"mechanized",ruleIds:["H3","truth-testimonies"],note:"Notícia/informação segue verdade/falsidade sem virar toda pergunta em III."},
  weather:{status:"mechanized",ruleIds:["H4","angles","Moon","sign-quality"],note:"Clima é módulo próprio, sem contaminar pergunta comum."},
  public_event:{status:"manual_context",ruleIds:["event-house","public-role","house-semantic-frame"],note:"A única parte manual é resolver semanticamente quem/qual função pública está em jogo; o núcleo não usa X como fallback universal."},
  adoption:{status:"mechanized",ruleIds:["H11-other-person-child","derived-H5"],note:"Criança a adotar é normalmente XI (V da VII), salvo relação específica com a criança."},
  lottery:{status:"mechanized",ruleIds:["H11-windfall","L2-pocket","jackpot-strength"],note:"Loteria é ganho do alto, distinta de aposta contra bookmaker."},
  election:{status:"manual_context",ruleIds:["candidate-perspective","Moon-electorate","incumbent-opponent","house-semantic-frame"],note:"Algoritmo político existe; a inteligência só precisa resolver a perspectiva/casas dos candidatos. Depois disso, o julgamento é mecanizado."},
  government_grant:{status:"mechanized",ruleIds:["H10-government","H11-government-gift","recipient"],note:"Governo e presente/dinheiro do governo são papéis distintos; recepção depende de ser direito ou concessão discricionária."},
  communication:{status:"mechanized",ruleIds:["H3-communication","derived-H3","Mercury-natural","service-H6"],note:"Comunicação é função; mensagem, prestador e serviço não são automaticamente a mesma casa."},
  service_change:{status:"mechanized",ruleIds:["provider-H6","natural-ruler","state-trigger","timing"],note:"Mudança/restauração/corte de serviço combina prestador, significador natural e gatilho concreto sem forçar uma casa universal do serviço."},
  delivery:{status:"mechanized",ruleIds:["seller-H7","package-2nd-from-seller","arrival"],note:"Pacote é posse de quem o detém até chegar; não é tratado como correspondência."},
  authenticity:{status:"mechanized",ruleIds:["product-2nd-from-supplier","essential-condition","affliction"],note:"Autenticidade/qualidade lê se o produto corresponde à sua natureza pela condição do significador."},
  kidnapping:{status:"mechanized",ruleIds:["relation-house","turned-H12","radical-and-turned-H8","release"],note:"Sequestro compõe sobrevivência, cativeiro, tratamento e soltura sem reduzir captor a L7 automático."},
  custom:{status:"manual_context",ruleIds:["house-semantic-atlas","recursive-turning","ambiguity-gate","audit"],note:"Não exige mais uma casa manual se semanticRoles forem fornecidos. A camada inteligente resolve a semântica; o núcleo compila relações recursivas e bloqueia ambiguidades."},
};

export function coverageFor(topic:HoraryTopic):HoraryCoverageEntry { return HORARY_TOPIC_COVERAGE[topic]; }
