export type ChineseModuleKey =
  | "bazi"
  | "ziwei"
  | "qimen"
  | "daliuren"
  | "taiyi"
  | "wenwanggua"
  | "tongshu";

export interface ChineseCatalogSection {
  title: string;
  description: string;
  topics: string[];
}

export interface ChineseModuleCatalog {
  key: ChineseModuleKey;
  label: string;
  shortDescription: string;
  longDescription: string;
  actionLabel: string;
  reportTitle: string;
  sections: ChineseCatalogSection[];
}

const BAZI_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Fundamentos do mapa",
    description: "Base estrutural do BaZi natal e da compatibilidade técnica.",
    topics: [
      "Quatro Pilares",
      "Pilar do Ano",
      "Pilar do Mês",
      "Pilar do Dia",
      "Pilar da Hora",
      "Troncos Celestes",
      "Ramos Terrestres",
      "Troncos ocultos",
      "Mestre do Dia",
      "Dez Deuses",
      "Cinco Elementos",
      "Yin/Yang",
      "Na Yin",
    ],
  },
  {
    title: "Calendário, estação e força",
    description: "Camadas que ajustam o relógio solar e medem a potência real do mapa.",
    topics: [
      "calendário solar por Jie Qi",
      "24 Jie Qi",
      "hora solar verdadeira",
      "mês de comando / Yue Ling",
      "força do Mestre do Dia",
      "De Ling",
      "De Di",
      "De Shi",
      "raiz dos Troncos / Tong Gen",
      "Troncos revelados / Tou Gan",
      "força por estação",
      "força por raiz",
      "força por apoio dos elementos",
      "旺相休囚死 — prosperidade, assistência, repouso, prisão e morte dos elementos",
      "12 fases de crescimento / Chang Sheng",
      "Na Yin dos pilares",
    ],
  },
  {
    title: "Relações, formações e vazios",
    description: "Choques, alianças, punições e padrões clássicos de transformação.",
    topics: [
      "Shen Sha / estrelas simbólicas",
      "Kong Wang / vazio",
      "combinações de Troncos",
      "combinações de Ramos",
      "choques",
      "punições",
      "autopunições",
      "danos",
      "destruições",
      "San He",
      "San Hui",
      "Liu He",
      "Liu Chong",
      "Liu Hai",
      "Liu Po",
      "Xing / punições",
      "formações de elemento",
      "transformações de elemento",
      "condições para transformação verdadeira",
      "força sazonal",
    ],
  },
  {
    title: "Estrutura e deuses úteis",
    description: "Classificação do mapa, deuses úteis e equilíbrio climático.",
    topics: [
      "estrutura do mapa",
      "Zheng Ge",
      "Cong Ge",
      "Hua Ge",
      "Zhuan Wang Ge",
      "estruturas especiais",
      "Yong Shen",
      "Xi Shen",
      "Ji Shen",
      "Chou Shen",
      "Xian Shen",
      "Tiao Hou",
      "Tiao Hou Yong Shen",
      "equilíbrio climático",
      "frio/calor/secura/umidade",
    ],
  },
  {
    title: "Referência por posição",
    description: "Recortes técnicos dos pilares e palácios derivados do mapa.",
    topics: [
      "referência técnica do Pilar do Ano",
      "referência técnica do Pilar do Mês",
      "referência técnica do Pilar do Dia",
      "referência técnica do Pilar da Hora",
      "Ramo do Dia",
      "Palácio do Cônjuge",
      "Tai Yuan",
      "Ming Gong",
      "Shen Gong",
    ],
  },
  {
    title: "Ciclos, trânsito e timing",
    description: "Camadas temporais do BaZi e suas interações entre destino e período.",
    topics: [
      "Da Yun",
      "Xiao Yun",
      "Liu Nian",
      "Liu Yue",
      "Liu Ri",
      "Liu Shi",
      "interação mapa natal + Da Yun",
      "interação mapa natal + Liu Nian",
      "interação Da Yun + Liu Nian",
      "interação Liu Nian + Liu Yue",
      "interação Liu Yue + Liu Ri",
      "interação Liu Ri + Liu Shi",
    ],
  },
  {
    title: "Dez Deuses e balanço elemental",
    description: "Distribuição fina dos Dez Deuses e do fluxo dos elementos.",
    topics: [
      "Shen Sha por pilar",
      "Kong Wang por pilar",
      "Dez Deuses nos Troncos visíveis",
      "Dez Deuses nos Troncos ocultos",
      "Dez Deuses por posição",
      "Dez Deuses por força",
      "Dez Deuses por ciclo de sorte",
      "estrutura útil e estrutura nociva",
      "elemento favorável",
      "elemento desfavorável",
      "elemento excessivo",
      "elemento ausente",
      "elemento bloqueado",
      "elemento transformado",
      "elemento de produção",
      "elemento de controle",
      "elemento de vazamento",
      "elemento de riqueza",
      "elemento de autoridade",
      "elemento de recurso",
      "elemento de expressão",
      "elemento de paridade",
    ],
  },
];

const ZI_WEI_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Palácios",
    description: "Distribuição do mapa Zi Wei Dou Shu pelos doze palácios.",
    topics: [
      "12 palácios",
      "Ming Gong",
      "Shen Gong",
      "palácio da vida",
      "palácio dos pais",
      "palácio da fortuna",
      "palácio da propriedade",
      "palácio da carreira",
      "palácio dos amigos/servidores",
      "palácio das viagens",
      "palácio da saúde",
      "palácio da riqueza",
      "palácio dos filhos",
      "palácio do casamento",
      "palácio dos irmãos",
    ],
  },
  {
    title: "Famílias estelares",
    description: "Categorias principais de estrelas usadas na leitura do mapa.",
    topics: [
      "14 estrelas principais",
      "estrelas auxiliares",
      "estrelas auspiciosas",
      "estrelas maléficas",
      "estrelas transformadoras",
      "estrelas menores",
    ],
  },
  {
    title: "Estrelas nomeadas",
    description: "Conjunto de estrelas individuais incluídas na leitura.",
    topics: [
      "Zi Wei",
      "Tian Ji",
      "Tai Yang",
      "Wu Qu",
      "Tian Tong",
      "Lian Zhen",
      "Tian Fu",
      "Tai Yin",
      "Tan Lang",
      "Ju Men",
      "Tian Xiang",
      "Tian Liang",
      "Qi Sha",
      "Po Jun",
      "Lu Cun",
      "Tian Ma",
      "Zuo Fu",
      "You Bi",
      "Wen Chang",
      "Wen Qu",
      "Tian Kui",
      "Tian Yue",
      "Qing Yang",
      "Tuo Luo",
      "Huo Xing",
      "Ling Xing",
      "Di Kong",
      "Di Jie",
      "Hong Luan",
      "Tian Xi",
      "Tian Yao",
      "Xian Chi",
    ],
  },
  {
    title: "Transformações e Flying Stars",
    description: "Quatro transformações e suas ativações ao longo do tempo.",
    topics: [
      "Quatro Transformações",
      "Hua Lu",
      "Hua Quan",
      "Hua Ke",
      "Hua Ji",
      "transformações natais",
      "transformações decenais",
      "transformações anuais",
      "transformações mensais",
      "transformações diárias",
      "Flying Stars / Fei Hua",
    ],
  },
  {
    title: "Estrutura e relações palacianas",
    description: "Relações entre palácios, brilho das estrelas e estados de força.",
    topics: [
      "San Fang Si Zheng",
      "palácio oposto",
      "palácios triangulares",
      "palácios associados",
      "estrelas em oposição",
      "estrelas em sanduíche",
      "brilho das estrelas",
      "força das estrelas",
      "exaltação/queda das estrelas",
      "12 Chang Sheng",
      "12 Bo Shi",
    ],
  },
  {
    title: "Ciclos e mapas derivados",
    description: "Leitura do destino nos recortes natal, decenal, anual e mensal.",
    topics: [
      "Da Xian",
      "Xiao Xian",
      "Liu Nian",
      "Liu Yue",
      "Liu Ri",
      "Liu Shi",
      "Ming Pan",
      "Da Xian Pan",
      "Liu Nian Pan",
      "Liu Yue Pan",
    ],
  },
  {
    title: "Interações e ativações",
    description: "Como palácios, estrelas e transformações se acendem no tempo.",
    topics: [
      "interação Ming Gong–Shen Gong",
      "interação entre palácios",
      "interação entre estrelas principais",
      "interação entre estrelas auxiliares",
      "interação entre Hua Lu, Hua Quan, Hua Ke e Hua Ji",
      "ativação por década",
      "ativação por ano",
      "ativação por mês",
      "ativação por dia",
    ],
  },
];

const QI_MEN_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Estrutura do tabuleiro",
    description: "Base espacial do mapa Qi Men Dun Jia.",
    topics: [
      "nove palácios",
      "oito portas",
      "nove estrelas",
      "oito deuses",
      "dez Troncos Celestes",
      "San Qi",
      "Liu Yi",
      "prato do Céu",
      "prato da Terra",
      "prato humano",
      "prato espiritual",
      "Heaven Plate",
      "Earth Plate",
      "Human Plate",
      "Spirit Plate",
    ],
  },
  {
    title: "Configuração temporal",
    description: "Abertura do Ju e dos ciclos superiores, médios e inferiores.",
    topics: [
      "Zhi Fu",
      "Zhi Shi",
      "Xun Shou",
      "Ju number",
      "Yin Dun",
      "Yang Dun",
      "Ju Yin",
      "Ju Yang",
      "24 Jie Qi",
      "Yuan superior",
      "Yuan médio",
      "Yuan inferior",
      "mapa anual",
      "mapa mensal",
      "mapa diário",
      "mapa horário",
      "mapa rotativo",
      "mapa voador",
    ],
  },
  {
    title: "Padrões e estruturas",
    description: "Formações auspiciosas, inauspiciosas e assinaturas especiais do tabuleiro.",
    topics: [
      "Kong Wang",
      "Ma Xing",
      "Fu Yin",
      "Fan Yin",
      "porta Fu Yin",
      "estrela Fu Yin",
      "deidade Fu Yin",
      "estruturas auspiciosas",
      "estruturas inauspiciosas",
      "combinações de San Qi",
      "San Qi De Shi",
      "San Qi Ru Mu",
      "Liu Yi Ji Xing",
      "Geng Ge",
    ],
  },
  {
    title: "Leitura por palácio",
    description: "Relações Céu-Terra e posicionamento dos marcadores do caso.",
    topics: [
      "tronco do Céu",
      "tronco da Terra",
      "relação Céu–Terra",
      "porta no palácio",
      "estrela no palácio",
      "deidade no palácio",
      "tronco no palácio",
      "palácio do sujeito",
      "palácio do objeto",
      "Yong Shen do caso",
    ],
  },
  {
    title: "Estratégia, direção e decisão",
    description: "Camadas usadas para ação prática, timing e eleição.",
    topics: [
      "direção",
      "estratégia",
      "decisão",
      "eleição",
      "divinação",
      "tempo de ação",
      "direção favorável",
      "direção desfavorável",
      "portas abertas/fechadas",
      "porta favorável",
      "porta desfavorável",
      "estrela favorável",
      "estrela desfavorável",
      "deidade favorável",
      "deidade desfavorável",
    ],
  },
];

const DA_LIU_REN_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Estrutura da lição",
    description: "Os elementos básicos do Da Liu Ren divinatório.",
    topics: [
      "quatro cursos",
      "quatro lições",
      "três transmissões",
      "transmissão inicial",
      "transmissão média",
      "transmissão final",
      "doze generais celestes",
      "doze ramos",
      "Heaven Plate",
      "Earth Plate",
      "Yue Jiang",
      "Tian Yi Gui Ren",
      "Stem of the day",
      "Branch of the day",
      "dia da consulta",
      "mês da consulta",
      "Kong Wang",
      "empty death",
    ],
  },
  {
    title: "Papéis e relações",
    description: "Sujeito, objeto e a lógica relacional da consulta.",
    topics: [
      "sujeito",
      "objeto",
      "guest",
      "host",
      "espírito útil",
      "espírito principal",
      "relação entre sujeito e objeto",
      "relação entre dia e mês",
      "relação entre curso e transmissão",
      "derivação das transmissões",
    ],
  },
  {
    title: "Classes de lição",
    description: "Assinaturas tradicionais usadas para classificar a resposta.",
    topics: [
      "classe principal",
      "tipos de lição",
      "Zeike",
      "Biyong",
      "Shehai",
      "Yaoke",
      "Maoxing",
      "Bieze",
      "Bakwa",
      "Fuyin",
      "Fanyin",
      "Bazhuan",
      "San Jiao",
      "Si Ke",
      "San Chuan",
    ],
  },
  {
    title: "Interações e resposta divinatória",
    description: "Leitura por Cinco Elementos, Yin/Yang e favorabilidade da resposta.",
    topics: [
      "interação por Cinco Elementos",
      "interação por Yin/Yang",
      "geração",
      "controle",
      "choque",
      "combinação",
      "punição",
      "dano",
      "vazio",
      "nobre celeste",
      "resposta horária/divinatória",
      "início, meio e fim do assunto",
      "força do curso",
      "força da transmissão",
      "favorabilidade do general",
      "favorabilidade do ramo",
      "favorabilidade do dia",
    ],
  },
];

const TAI_YI_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Fundação do sistema",
    description: "Estrutura numérica e temporal do Tai Yi Shen Shu.",
    topics: [
      "Tai Yi",
      "Tai Yi board",
      "Tai Yi palace",
      "Tai Yi number",
      "cálculo imperial/mundano",
      "cálculo do Ju",
      "ciclos maiores",
      "ciclos anuais",
      "ciclos mensais",
      "ciclos diários",
      "ciclos horários",
      "Wen Tai Yi",
      "Wu Tai Yi",
    ],
  },
  {
    title: "Host e guest",
    description: "Relações entre governante, evento e generais do caso.",
    topics: [
      "host",
      "guest",
      "host general",
      "guest general",
      "palácio do governante",
      "palácio do evento",
      "relação host/guest",
    ],
  },
  {
    title: "Deuses e direção",
    description: "Camadas auspiciosas, inauspiciosas e vetores de vantagem ou perigo.",
    topics: [
      "deuses auspiciosos",
      "deuses inauspiciosos",
      "direção de vantagem",
      "direção de perigo",
    ],
  },
  {
    title: "Tempo coletivo e presságio",
    description: "Leitura mundana, militar e política do tempo cósmico.",
    topics: [
      "cálculos de acumulação temporal",
      "estados",
      "guerras",
      "clima coletivo",
      "destino político",
      "eventos públicos",
      "presságio coletivo",
      "estrutura militar/mundana",
      "estrutura cósmica de tempo",
      "Tai Yi anual",
      "Tai Yi mensal",
      "Tai Yi diário",
      "Tai Yi horário",
    ],
  },
];

const WEN_WANG_GUA_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Hexagramas e linhas",
    description: "Arquitetura do Wen Wang Gua e os formatos centrais do hexagrama.",
    topics: [
      "64 hexagramas",
      "oito palácios",
      "hexagrama principal",
      "hexagrama transformado",
      "hexagrama nuclear",
      "hexagrama de seis choques",
      "hexagrama de seis combinações",
      "linhas móveis",
      "linhas fixas",
      "seis linhas",
      "seis parentes",
      "seis animais",
    ],
  },
  {
    title: "Mapeamento e papéis",
    description: "Atribuições de Troncos, Ramos, elementos e linhas de resposta.",
    topics: [
      "Na Jia",
      "Troncos Celestes nas linhas",
      "Ramos Terrestres nas linhas",
      "elemento de cada linha",
      "palácio do hexagrama",
      "elemento do palácio",
      "Shi Yao",
      "Ying Yao",
      "linha mundo",
      "linha resposta",
    ],
  },
  {
    title: "Sistema de Shen",
    description: "Relações entre Yong Shen, Yuan Shen e demais espíritos auxiliares.",
    topics: [
      "Yong Shen",
      "Yuan Shen",
      "Ji Shen",
      "Chou Shen",
      "Fu Shen",
      "Fei Shen",
      "Jin Shen",
      "Tui Shen",
    ],
  },
  {
    title: "Transformações das linhas",
    description: "Estados, mutações e qualidade temporal de cada linha.",
    topics: [
      "Hua Jin",
      "Hua Tui",
      "Hua Po",
      "Hua Kong",
      "Hua Mu",
      "Hua Jue",
      "Hua Hui Tou Sheng",
      "Hua Hui Tou Ke",
      "linha escondida",
      "linha revelada",
      "linha forte",
      "linha fraca",
      "linha próspera pelo mês",
      "linha próspera pelo dia",
      "linha quebrada pelo mês",
      "linha quebrada pelo dia",
    ],
  },
  {
    title: "Tempo, vazio e interação",
    description: "Força temporal e relações entre as linhas e o momento da consulta.",
    topics: [
      "Yue Jian",
      "Ri Chen",
      "Yue Po",
      "Ri Po",
      "Xun Kong",
      "Kong Wang",
      "vazio",
      "choque",
      "combinação",
      "geração",
      "controle",
      "Liu Chong",
      "Liu He",
      "San He Ju",
      "tumba/armazém",
      "nascimento",
      "prosperidade",
      "morte",
      "decadência",
      "dia e mês da consulta",
    ],
  },
  {
    title: "Relações interpretativas",
    description: "Leitura final das conexões entre hexagramas, linhas e Yong Shen.",
    topics: [
      "relação entre hexagrama original e transformado",
      "relação entre linha mundo e linha resposta",
      "relação entre Yong Shen e Yuan Shen",
      "relação entre Yong Shen e Ji Shen",
      "relação entre Yong Shen e Chou Shen",
      "força temporal da linha",
      "força elemental da linha",
      "movimento da linha",
      "transformação da linha",
    ],
  },
];

const TONG_SHU_SECTIONS: ChineseCatalogSection[] = [
  {
    title: "Calendários e estruturas",
    description: "Camadas calendáricas e marcadores clássicos do Tong Shu.",
    topics: [
      "calendário chinês",
      "calendário solar",
      "calendário lunar",
      "mês lunar",
      "mês intercalar",
      "60 Jia Zi",
      "24 Jie Qi",
      "12 oficiais",
      "Jian Chu",
      "28 mansões lunares",
      "28 Xiu",
      "Tai Sui",
      "Sui Po",
      "San Sha",
      "Five Yellow",
      "Year Breaker",
      "Month Breaker",
      "Day Breaker",
      "Peng Zu Bai Ji",
      "Dong Gong",
    ],
  },
  {
    title: "Auspiciosidade",
    description: "Filtros de favorabilidade para dia, hora e estrelas do calendário.",
    topics: [
      "dias auspiciosos",
      "dias inauspiciosos",
      "horas auspiciosas",
      "horas inauspiciosas",
      "estrelas do dia",
      "estrelas auspiciosas",
      "estrelas nocivas",
      "Heavenly Virtue",
      "Monthly Virtue",
      "Heavenly Doctor",
      "Nobleman days",
    ],
  },
  {
    title: "Compatibilidade e seleção",
    description: "Critérios de encaixe entre o dia, a pessoa, a direção e outras técnicas.",
    topics: [
      "animal clash do dia",
      "compatibilidade dia–pessoa",
      "compatibilidade dia–atividade",
      "compatibilidade dia–direção",
      "compatibilidade do dia com BaZi",
      "seleção por BaZi",
      "seleção por Qi Men",
      "seleção por Xuan Kong Da Gua",
      "seleção por San He",
      "seleção por San Yuan",
      "seleção por 24 montanhas",
      "seleção por 28 mansões",
      "seleção por 12 oficiais",
      "seleção por Tai Sui",
      "seleção por San Sha",
      "seleção por Tong Shu",
    ],
  },
  {
    title: "Atividades",
    description: "Uso prático do calendário para ações permitidas, proibidas e neutras.",
    topics: [
      "atividade permitida",
      "atividade proibida",
      "atividade neutra",
      "casamento",
      "mudança",
      "construção",
      "demolição",
      "viagem",
      "abertura de negócio",
      "assinatura",
      "sepultamento",
      "culto ancestral",
      "corte de cabelo",
      "tratamento médico",
      "compra",
      "instalação de porta",
      "instalação de cama",
      "fogão",
      "reforma",
      "início de obra",
    ],
  },
];

export const CHINESE_MODULE_CATALOG: Record<ChineseModuleKey, ChineseModuleCatalog> = {
  bazi: {
    key: "bazi",
    label: "Bazi",
    shortDescription:
      "Mapa natal, sinastria BaZi e ciclos de sorte reunidos em um quadro técnico calculado.",
    longDescription:
      "Quadro técnico do BaZi com pilares, forças, combinações, clima, Yong Shen, ciclos, sinastria e catálogo completo de informações calculadas.",
    actionLabel: "Calcular relatório BaZi",
    reportTitle: "Relatório Técnico BaZi",
    sections: BAZI_SECTIONS,
  },
  ziwei: {
    key: "ziwei",
    label: "Zi Wei Dou Shu",
    shortDescription:
      "Palácios, estrelas, transformações e ativações temporais do sistema imperial.",
    longDescription:
      "Leitura por Ming Gong, Shen Gong, palácios, estrelas e transformações ao longo do destino.",
    actionLabel: "Gerar leitura Zi Wei Dou Shu",
    reportTitle: "Relatório Zi Wei Dou Shu",
    sections: ZI_WEI_SECTIONS,
  },
  qimen: {
    key: "qimen",
    label: "Qi Men Dun Jia",
    shortDescription:
      "Portas, estrelas, deuses, Ju e direção estratégica para decisão e eleição.",
    longDescription:
      "Painel técnico do Qi Men Dun Jia para leitura de estratégia, direção, tempo e configuração do caso.",
    actionLabel: "Gerar painel Qi Men Dun Jia",
    reportTitle: "Relatório Qi Men Dun Jia",
    sections: QI_MEN_SECTIONS,
  },
  daliuren: {
    key: "daliuren",
    label: "Da Liu Ren",
    shortDescription:
      "Quatro lições, três transmissões e classes de lição para resposta divinatória.",
    longDescription:
      "Estrutura tradicional do Da Liu Ren com sujeito, objeto, cursos, transmissões e favorabilidades.",
    actionLabel: "Gerar leitura Da Liu Ren",
    reportTitle: "Relatório Da Liu Ren",
    sections: DA_LIU_REN_SECTIONS,
  },
  taiyi: {
    key: "taiyi",
    label: "Tai Yi Shen Shu",
    shortDescription:
      "Leitura cósmica de tempo, host/guest, presságios coletivos e direção de vantagem.",
    longDescription:
      "Mapa técnico do Tai Yi para ciclos, governante, evento, clima coletivo e estrutura mundana.",
    actionLabel: "Gerar painel Tai Yi Shen Shu",
    reportTitle: "Relatório Tai Yi Shen Shu",
    sections: TAI_YI_SECTIONS,
  },
  wenwanggua: {
    key: "wenwanggua",
    label: "Wen Wang Gua",
    shortDescription:
      "Hexagramas, linhas móveis, Yong Shen e relações temporais do método de seis linhas.",
    longDescription:
      "Leitura técnica do Wen Wang Gua com Na Jia, Shen das linhas, forças e transformações.",
    actionLabel: "Gerar leitura Wen Wang Gua",
    reportTitle: "Relatório Wen Wang Gua",
    sections: WEN_WANG_GUA_SECTIONS,
  },
  tongshu: {
    key: "tongshu",
    label: "Tong Shu",
    shortDescription:
      "Calendário tradicional com seleção de datas, horas, direções e atividades.",
    longDescription:
      "Painel de Tong Shu com auspiciosidade do dia, filtros de seleção e atividades recomendadas.",
    actionLabel: "Gerar leitura Tong Shu",
    reportTitle: "Relatório Tong Shu",
    sections: TONG_SHU_SECTIONS,
  },
};

export function getModuleTopicCount(moduleKey: ChineseModuleKey) {
  return CHINESE_MODULE_CATALOG[moduleKey].sections.reduce(
    (total, section) => total + section.topics.length,
    0
  );
}

export function flattenModuleTopics(moduleKey: ChineseModuleKey) {
  return CHINESE_MODULE_CATALOG[moduleKey].sections.flatMap((section) => section.topics);
}

export function catalogSectionsToReport(sections: ChineseCatalogSection[]) {
  return sections
    .map((section) =>
      [section.title.toUpperCase(), section.description, ...section.topics.map((topic) => `- ${topic}`)].join(
        "\n"
      )
    )
    .join("\n\n");
}
